# version: '3.8' # obsolete

services:
  pricewebapi:
    build:
      platforms:
        - linux/arm64
    image: igncdev/price-web-api:arm64
    volumes:
      - /home/pi/Desktop/certs:/app/certs:ro

    ports:
      - "8080:8080"
      - "8081:8081"
    
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/cloudflare.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cloudflare
        - CERT_PASSWORD=cloudflare
    restart: unless-stopped