services:
  pricewebapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./certs:/app/certs:ro
      - ./Data/pricewebapi:/data/pricewebapi
    environment:
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/cloudflare.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cloudflare
      - CERT_PASSWORD=cloudflare
    restart: unless-stopped
