// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using price_web_api.Data;

#nullable disable

namespace price_web_api.Migrations
{
    [DbContext(typeof(PriceContext))]
    partial class PriceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("price_web_api.Models.Investment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Investments");

                    b.HasDiscriminator().HasValue("Investment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("price_web_api.Models.MinimalPriceRec", b =>
                {
                    b.Property<string>("symbol")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvestmentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("symbol", "date");

                    b.HasIndex("InvestmentId");

                    b.ToTable("PriceRecords");
                });

            modelBuilder.Entity("price_web_api.Models.Fund", b =>
                {
                    b.HasBaseType("price_web_api.Models.Investment");

                    b.Property<string>("ISIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MorningStarId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Fund");
                });

            modelBuilder.Entity("price_web_api.Models.PreciousMetal", b =>
                {
                    b.HasBaseType("price_web_api.Models.Investment");

                    b.HasDiscriminator().HasValue("PreciousMetal");
                });

            modelBuilder.Entity("price_web_api.Models.MinimalPriceRec", b =>
                {
                    b.HasOne("price_web_api.Models.Investment", null)
                        .WithMany("Prices")
                        .HasForeignKey("InvestmentId");
                });

            modelBuilder.Entity("price_web_api.Models.Investment", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
